# Generated by Django 4.1.6 on 2023-02-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='month',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ip',
            name='year',
            field=models.DateField(db_index=True),
        ),
    ]
