# Generated by Django 4.1.6 on 2023-02-13 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ip_month_alter_ip_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='month',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ip',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
