# Generated by Django 4.1.6 on 2023-02-16 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_description_kz_service_description_kz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='baskets',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
